# Generated by Django 4.2.2 on 2023-06-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='site',
            field=models.CharField(choices=[('https://mahsulot.com/order_api/', 'mahsulot.com')], default=11, max_length=255),
            preserve_default=False,
        ),
    ]
